name: Weekly Deploy

on:
  schedule:
  - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Post to Vercel deploy hook
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_KkYxnlBBP4BYoPdxAv9LS7QXuS0f/7bKMcLbhp6

